apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-1
spec:
  containers:
  - name: gpu-container
    image: tovitu/instruct-flamingo:latest
    command: ["sleep", "infinity"]
    resources:
          requests:
            cpu: "1"
            memory: "16Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu: 2
    env:
      - name: "DATASET_DIR"
        value: "/external/"
      - name: "CHECKPOINT_DIR"
        value: "/external/models/"
    volumeMounts:
      - mountPath: "/external"
        name: external

  volumes:
    - name: external
      persistentVolumeClaim:
        claimName: tovi-vol
  

    
